### ISSUE TITLE
Port projects from RustcSerialize to Serde

### ISSUE THREAD

**Issue by itpetey** [intecture/api#26]
Awaiting stabilization of macros 1.1.

**Comment by dtolnay** [comment]
Ready to go! Macros 1.1 is stable in Rust 1.15.0.

**Comment by itpetey** [comment]
I totally missed the 1.15 cycle, then when I did look there was 1.15.1 * 4!

**Comment by itpetey** [comment]
Fixed by 57d3b7e.
