### ISSUE TITLE
Update to serde 0.9

### ISSUE THREAD

**Issue by dtolnay** [intecture/api#33]
Among other benefits, the 0.9 JSON value is a lot nicer to work with. This line in api/src/host/data/mod.rs:

```rust
me.as_object_mut().unwrap().insert("_payloads".into(), serde_json::to_value(payloads));
```

could be:

```rust
me["_payloads"] = json!(payloads);
```

**Comment by itpetey** [comment]
Oh nice! I'll definitely take a look. Thanks for the suggestion mate :)
