### ISSUE TITLE
Add support for NixOS

### ISSUE THREAD

**Issue by rushmorem** [intecture/api#34]
https://github.com/intecture/cli/issues/8#issuecomment-280884064

**Comment by rushmorem** [comment]
Waiting for https://github.com/intecture/api/issues/14...

**Comment by itpetey** [comment]
Oh sorry I forgot to address that question. No best not to wait for that. It'll take quite a bit of work and I have a lot of other stuff (like a new CI) on my plate at the moment so pretend that ticket's not there :)

**Comment by rushmorem** [comment]
OK, noted. Thanks :)
